### 全件取得
GET http://localhost/home

### 条件付き検索
GET http://localhost/home?city=沖縄県&minPrice=1000&maxPrice=100000&propertyType=RESIDENTIAL

### 1件取得
GET http://localhost/home/1

### 登録
POST http://localhost/home
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib2themFraSIsImlkIjozLCJpYXQiOjE2NDc1NzMzNjcsImV4cCI6MTY1MTE3MzM2N30.IpXvituAkE5-QT_hPVxza8tMVSurIZuX2cIjWmEdda0

{
  "address": "piyopiyo 132",
  "numberOfBedrooms": 4,
  "numberOfBathrooms": 1,
  "city": "大阪府",
  "price": 123456,
  "landSize": 1200,
  "propertyType": "RESIDENTIAL",
  "images": [
    {
      "url": "post image1"
    },
    {
      "url": "post image2"
    }
  ]
}

### 更新
PUT http://localhost/home/6
content-type: application/json

{
  "address": "piyopiyo 1321"
}

### 削除
DELETE http://localhost/home/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaG9nZSIsImlkIjoyLCJpYXQiOjE2NDc1MTQ4OTEsImV4cCI6MTY1MTExNDg5MX0.OFJlOu3YUzvmk-S7Beip5E2CClufDH8t0HsDKf3C8fE

### お問い合わせ
POST http://localhost/home/1/inquire
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoib2themFraSIsImlkIjozLCJpYXQiOjE2NDc1NzMzNjcsImV4cCI6MTY1MTE3MzM2N30.IpXvituAkE5-QT_hPVxza8tMVSurIZuX2cIjWmEdda0

{
  "message": "hello world"
}
