POST http://localhost/auth/signup
content-type: application/json

{
  "name": "hoge",
  "phone": "000-0000-0000",
  "email": "rui@hoge.com",
  "password": "123456"
}

###

POST http://localhost/auth/signin
content-type: application/json

{
  "email": "rui@hoge.com",
  "password": "123456"
}








