POST http://localhost:3000/auth/signup/BUYER
content-type: application/json

{
  "name": "okazaki",
  "phone": "000-0000-0000",
  "email": "okazaki@hoge.com",
  "password": "123456",
  "productKey": "$2a$10$hap/PXH7HUCQkPsO5CcaNeRgkVifnZ7IfuVlJUBsNgfJom9lgTyJm"
}

###

POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "rui@hoge.com",
  "password": "123456"
}

###

POST http://localhost:3000/auth/key
content-type: application/json

{
  "email": "rui13@hoge.com",
  "userType": "REALTOR"
}

###

Get http://localhost:3000/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiaG9nZSIsImlkIjoyLCJpYXQiOjE2NDc1MTQ4OTEsImV4cCI6MTY1MTExNDg5MX0.OFJlOu3YUzvmk-S7Beip5E2CClufDH8t0HsDKf3C8fE